### ISSUE TITLE
REDMI NOTE 7 BOOTLOOP

### ISSUE THREAD

**Issue by fireantares1** [RohanDebroy/Greenify4Magisk#1]
I added privapp_white list com.oasisfeng.greenify to etc in zip and it fixed the problem

**Comment by RohanDebroy** [comment]
The privapp whitelisting is already done. It shouldn't have caused any issues for you.
If possible, can you raise a PR with the fix that you have applied.

**Comment by fireantares1** [comment]
https://drive.google.com/file/d/1yZVqMlSbEYI7Mz9SX295LkpfezbujYkJ/view?usp=sharing

**Comment by fireantares1** [comment]
> The privapp whitelisting is already done. It shouldn't have caused any issues for you. If possible, can you raise a PR with the fix that you have applied.

https://drive.google.com/file/d/1yZVqMlSbEYI7Mz9SX295LkpfezbujYkJ/view?usp=sharing

**Comment by RohanDebroy** [comment]
Thank you very much. I'll try to update this to the latest magisk version.
