### ISSUE TITLE
System API of 32 greater than maximum...

### ISSUE THREAD

**Issue by WasteOfO2** [RohanDebroy/Greenify4Magisk#2]
Phone: One Plus 5
ROM: Lineage OS 19-20220801-NIGHTLY-cheeseburger

`! Your system API of 32 is greater than the maximum API of 29!`

The installation fails due to this error

**Comment by RohanDebroy** [comment]
The older zip only supports android 10. Try this zip and Flash at your own risk.

[Greenify4Magisk-v4.7.8(BETA).zip](https://github.com/RohanDebroy/Greenify4Magisk/files/9252941/Greenify4Magisk-v4.7.8.BETA.zip)

**Comment by WasteOfO2** [comment]
Got it, thx!
